spring.application.name=applicationtracker

# Database connection settings
spring.datasource.url=jdbc:h2:file:./data/jobtrackerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA / Hibernate configuration
# Automatically updates your database schema to match your Java @Entity classes

# Use this is final / prod
spring.jpa.hibernate.ddl-auto=update

# For refreshing the schema
#spring.jpa.hibernate.ddl-auto=create

# Prints your actual SQL queries to the terminal logs (helpful for debugging)
spring.jpa.show-sql=true

# Enable the visual H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Fixes view rendering issues inside the H2 web console frame
spring.h2.console.settings.web-allow-others=false